### ISSUE TITLE
AssertionError: leaf variable was used in an inplace operation

### ISSUE THREAD

**Issue by ghost** [ypxie/pytorch-NeuCom#1]
Hi thanks for sharing this, it's really cool that you managed to get it working :+1:

I got an error though when trying to run the repo,

```(pyphi) ajay@ajay-h8-1170uk:~/PythonProjects/pytorch_NeuCom_v1$ python train.py
Iteration 0/100000Traceback (most recent call last):
  File "train.py", line 155, in <module>
    loss.backward()
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/torch/autograd/variable.py", line 158, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/torch/autograd/variable.py", line 201, in _do_backward
    "leaf variable was used in an inplace operation"
AssertionError: leaf variable was used in an inplace operation
``` 

I've seen this before but I can't remember how to fix it? Can you suggest anything please?

Also maybe there's a typo on the "how to run" part of the cover page for the repo, I think it should be ,

```python tasks/Copy/train.py```

Thanks a lot for your help :+1:

**Comment by ypxie** [comment]
Thanks for pointing out the typo :D 
Are you using the latest version of pytorch?  I just tested it and it runs on my computer.
Also, I only tested it with python 2.7.
Hope it helps.

**Comment by ghost** [comment]
Hi @ypxie thanks for replying. 

Sorry, about this, I can firm its running/training, with python 3.5/ubuntu 14.04lts, and a fresh conda install of pytorch-0.1.9.

Will let you know if there's anything else that might help, and hopefully train it on some other test problems :+1: 

Best regards,

Aj

**Comment by ghost** [comment]
Update - I had to build PyTorch from source, (not conda install), on another machine, with an old GPU, to get this working. 

So try giving that a go, if you run into GPU type errors, or get memory leak from running on the CPU/without CUDA.

**Comment by ypxie** [comment]
Thanks for sharing your experience. :D
